Avoid adding Timeplot because it is failing.
The exception produced is:
org.zkoss.zk.ui.UiException: Widget class required for <Timeplot z_d__87> with default
at org.zkoss.zk.ui.AbstractComponent.redraw(AbstractComponent.java:1681)

The root cause is that timeplotz lang-addon.xml file is not loaded due
to a version missmatch. From startup log:

Aug 26, 2010 8:21:27 PM org.zkoss.zk.ui.sys.ConfigParser checkVersion:120
INFO: Ignore jar:file:/home/ogonzalez/.m2/repository/org/zkoss/zkforge/timeplotz/1.1_50/timeplotz-1.1_50.jar!/metainfo/zk/lang-addon.xml
Cause: version not matched; expected=1.1_50-FL, xml=1.1_50

FEA: ItEr02S03MigracionZK5