Reverted commit "bump jasper dependencies" to avoid errors with reports. Pulled to master in https://github.com/LibrePlan/libreplan/pull/1949
HTTP ERROR 410
Problem accessing /zkau/view/z_gm7/oJ2Q69/rev/0/hoursWorkedPerWorkerReport.html. Reason:

    Failed to load /view/z_gm7/oJ2Q69/rev/0/hoursWorkedPerWorkerReport.html

Cause:
net.sf.jasperreports.engine.JRException: Class not found when loading object from InputStream.