Revert "Revert "Revert "Error message java.lang.NoClassDefFoundError: org/hibernate/util/DTDEntityResolver"""
This reverts commit 5a4e5b408a0e52ca06d3fe232aafbffb4b1c3b3e.