Revert "Revert "Error message java.lang.NoClassDefFoundError: org/hibernate/util/DTDEntityResolver""
This reverts commit 16f3a2ac84631ea2ae836c3967fe15feba3a8384.