Avoid LazyInitializationException accessing template's labels
This exception happened after saving and continuing due to labels not
being in the session.

ERROR org.hibernate.LazyInitializationException  - failed to lazily initialize a collection of role: org.navalplanner.business.templates.entities.OrderElementTemplate.labels, no session or session was closed
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.navalplanner.business.templates.entities.OrderElementTemplate.labels, no session or session was closed

FEA: ItEr68S04BugFixing