Revert "Error message java.lang.NoClassDefFoundError: org/hibernate/util/DTDEntityResolver"
This reverts commit 94e33544fe6e039e2e9a0cfd124cddc2f00f7551.